[build]
cmd = "go build -o ./tmp/main ./cmd/app"
bin = "tmp/main"
full_bin = "tmp/main"
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html", "proto"]
exclude_file = []
delay = 1000 # ms
stop_on_error = true
args_bin = []
args_runner = []
output = "stdout"

[log]
time = false

[watch]
full = true